name: dlproject
channels:
- defaults
- conda-forge
dependencies:
- ca-certificates=2018.03.07
- certifi=2018.10.15
- libedit=3.1.20170329
- libffi=3.2.1
- ncurses=6.1
- openssl=1.1.1
- pip=10.0.1
- python=3.6.7
- readline=7.0
- setuptools=40.4.3
- sqlite=3.25.2
- tk=8.6.8
- wheel=0.32.2
- xz=5.2.4
- zlib=1.2.11
- pip:
  - absl-py==0.6.0
  - astor==0.7.1
  - backcall==0.1.0
  - bleach==3.0.2
  - chardet==3.0.4
  - cycler==0.10.0
  - decorator==4.3.0
  - defusedxml==0.5.0
  - entrypoints==0.2.3
  - gast==0.2.0
  - googledrivedownloader==0.3
  - grpcio==1.16.0
  - h5py==2.8.0
  - idna==2.7
  - ipykernel==5.1.0
  - ipython==7.1.1
  - ipython-genutils==0.2.0
  - ipywidgets==7.4.2
  - jedi==0.13.1
  - jinja2==2.10
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.2.3
  - jupyter-console==6.0.0
  - jupyter-core==4.4.0
  - keras==2.2.4
  - keras-applications==1.0.6
  - keras-preprocessing==1.0.5
  - kiwisolver==1.0.1
  - markdown==3.0.1
  - markupsafe==1.0
  - matplotlib==3.0.1
  - mistune==0.8.4
  - nbconvert==5.4.0
  - nbformat==4.4.0
  - notebook==5.7.0
  - numpy==1.15.3
  - opencv-python==3.4.3.18
  - pandas==0.23.4
  - pandocfilters==1.4.2
  - parso==0.3.1
  - pexpect==4.6.0
  - pickleshare==0.7.5
  - pillow==5.3.0
  - prometheus-client==0.4.2
  - prompt-toolkit==2.0.6
  - protobuf==3.6.1
  - ptyprocess==0.6.0
  - pygments==2.2.0
  - pyparsing==2.2.2
  - python-dateutil==2.7.5
  - pytz==2018.7
  - pyyaml==3.13
  - pyzmq==17.1.2
  - qtconsole==4.4.2
  - requests==2.20.0
  - scipy==1.1.0
  - send2trash==1.5.0
  - six==1.11.0
  - tensorboard==1.11.0
  - tensorflow==1.11.0
  - termcolor==1.1.0
  - terminado==0.8.1
  - testpath==0.4.2
  - tornado==5.1.1
  - tqdm==4.28.1
  - traitlets==4.3.2
  - urllib3==1.24
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - werkzeug==0.14.1
  - widgetsnbextension==3.4.2
  - torch==0.4.1
  - torchvision==0.2.1
  - scrapy==1.5.1
  - scikit-image==0.14.1
